version: "3.8"

services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iposdb
    volumes:
      - ipos_pgdata:/var/lib/postgresql/data

volumes:
  ipos_pgdata:
